// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace DataBinding
{
	public partial class CustomView : NSView
	{
		public CustomView (IntPtr handle) : base (handle)
		{
		}
	}
}
