// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace DataBinding
{
	public partial class TableViewController : NSView
	{
		private NSMutableArray _people = new NSMutableArray();

		[Export("personModelArray")]
		public NSArray People
		{
			get { return _people; }
		}


		public TableViewController (IntPtr handle) : base (handle)
		{
		}

		[Export("addObject:")]
		public void AddPerson(PersonModel person)
		{
			WillChangeValue("personModelArray");
			_people.Add(person);
			DidChangeValue("personModelArray");
		}

		[Export("insertObject:inPersonModelArrayAtIndex:")]
		public void InsertPerson(PersonModel person, nint index)
		{
			WillChangeValue("personModelArray");
			_people.Insert(person, index);
			DidChangeValue("personModelArray");
		}

		[Export("removeObjectFromPersonModelArrayAtIndex:")]
		public void RemovePerson(nint index)
		{
			WillChangeValue("personModelArray");
			_people.RemoveObject(index);
			DidChangeValue("personModelArray");
		}

		[Export("setPersonModelArray:")]
		public void SetPeople(NSMutableArray array)
		{
			WillChangeValue("personModelArray");
			_people = array;
			DidChangeValue("personModelArray");
		}

		public override void AwakeFromNib()
		{
			base.AwakeFromNib();

			// Build list of employees
			AddPerson(new PersonModel("Craig Dunn", "Documentation Manager", true));
			AddPerson(new PersonModel("Amy Burns", "Technical Writer"));
			AddPerson(new PersonModel("Joel Martinez", "Web & Infrastructure"));
			AddPerson(new PersonModel("Kevin Mullins", "Technical Writer"));
			AddPerson(new PersonModel("Mark McLemore", "Technical Writer"));
			AddPerson(new PersonModel("Tom Opgenorth", "Technical Writer"));
			AddPerson(new PersonModel("Larry O'Brien", "API Documentation Manager", true));
			AddPerson(new PersonModel("Mike Norman", "API Documenter"));

		}
	}
}
